CREATE TABLE interview_questions (
    id UUID PRIMARY KEY,
    topic VARCHAR(100) NOT NULL,
    type VARCHAR(30) NOT NULL,
    difficulty VARCHAR(20) NOT NULL,
    prompt TEXT NOT NULL,
    reference_answer TEXT NOT NULL,
    evaluation_keywords TEXT NOT NULL
);

CREATE INDEX idx_interview_questions_topic_difficulty
    ON interview_questions (topic, difficulty);

INSERT INTO interview_questions (id, topic, type, difficulty, prompt, reference_answer, evaluation_keywords) VALUES
(gen_random_uuid(), 'Java', 'TECHNICAL', 'MEDIUM',
 'Explain the difference between HashMap and ConcurrentHashMap. When would you use each?',
 'HashMap is not thread-safe and is suitable when a map is confined to one thread or externally synchronized. ConcurrentHashMap is designed for concurrent access and provides thread-safe operations with better concurrency than synchronizing an entire map.',
 'hashmap,concurrenthashmap,thread,thread-safe,concurrency,synchronization'),
(gen_random_uuid(), 'Java', 'TECHNICAL', 'HARD',
 'Explain Java Streams and describe a practical use case for flatMap.',
 'Collections hold data while streams describe a lazy computation pipeline over data. flatMap converts each input element into a stream and flattens the resulting streams, such as converting List<List<String>> into one Stream<String>.',
 'stream,collection,pipeline,lazy,flatmap,flatten'),
(gen_random_uuid(), 'OOPS Concepts', 'TECHNICAL', 'MEDIUM',
 'Explain polymorphism in Java with a practical example.',
 'Polymorphism allows a parent type or interface to refer to different concrete implementations. With method overriding, the implementation selected at runtime depends on the actual object.',
 'polymorphism,overriding,runtime,interface,parent,implementation'),
(gen_random_uuid(), 'Spring Boot', 'TECHNICAL', 'MEDIUM',
 'Why is constructor injection preferred over field injection in Spring?',
 'Constructor injection makes dependencies explicit, supports final fields and immutability, prevents partially initialized objects, and makes unit testing simple without reflection.',
 'constructor,injection,dependency,immutable,test,final'),
(gen_random_uuid(), 'Spring Boot', 'SCENARIO', 'HARD',
 'A Spring Boot API returns intermittent 500 errors in production. Walk through your troubleshooting approach.',
 'Start with correlation or request IDs and application logs, identify the exception and failing dependency, inspect metrics and health endpoints, check recent deployments and infrastructure, reproduce safely, fix the root cause, and verify with regression tests.',
 'log,correlation,exception,metric,health,dependency,deployment,root cause'),
(gen_random_uuid(), 'Microservices', 'TECHNICAL', 'MEDIUM',
 'Explain the Saga pattern and why it is useful in distributed transactions.',
 'A Saga splits a business transaction into local transactions. Each successful step commits locally, and a failure triggers compensating actions. This avoids a distributed two-phase database transaction across services.',
 'saga,transaction,local,compensating,service,event,distributed'),
(gen_random_uuid(), 'Microservices', 'SCENARIO', 'HARD',
 'Payment succeeds but the order service times out. How do you prevent duplicate payment and reconcile the order?',
 'Use an idempotency key for payment initiation, persist the payment result, make retries safe, publish durable payment events, and reconcile order and payment state asynchronously.',
 'idempotency,payment,retry,event,status,reconcile,persist'),
(gen_random_uuid(), 'Programming Round', 'CODING', 'MEDIUM',
 'Given an integer array, find the first non-repeating element and explain the time and space complexity.',
 'Count frequencies using a HashMap in one pass, then scan the original array in order and return the first value with frequency one. Time complexity is O(n) and extra space is O(n).',
 'map,frequency,hash,o(n),two pass,count'),
(gen_random_uuid(), 'Programming Round', 'CODING', 'HARD',
 'How would you detect a cycle in a linked list without using extra space?',
 'Use Floyd’s tortoise-and-hare algorithm. Move slow by one node and fast by two nodes. If they meet, a cycle exists. The algorithm is O(n) time and O(1) extra space.',
 'floyd,slow,fast,two pointer,cycle,o(1)'),
(gen_random_uuid(), 'React', 'TECHNICAL', 'MEDIUM',
 'Explain controlled components in React and why they are useful for forms.',
 'A controlled input gets its value from React state and updates through an event handler. React becomes the source of truth, making validation and form behavior predictable.',
 'controlled,state,value,onchange,form,source of truth');
