import { useState } from 'react';
import Editor from '@monaco-editor/react';

const LANGS: Record<string,string> = {java:'Java',python:'Python',javascript:'JavaScript',typescript:'TypeScript',cpp:'C++',csharp:'C#',go:'Go',rust:'Rust',kotlin:'Kotlin',php:'PHP',ruby:'Ruby',swift:'Swift',sql:'SQL'};
const START: Record<string,string> = {java:'public class Solution {\n  public static void main(String[] args) {\n    System.out.println("Hello BerryBot");\n  }\n}',python:'# Write your solution here\ndef solution():\n    pass',javascript:'function solution(input) {\n  return input;\n}',typescript:'function solution(input: string): string {\n  return input;\n}',cpp:'#include <bits/stdc++.h>\nusing namespace std;\nint main() { return 0; }',csharp:'using System;\nclass Solution { static void Main() {} }',go:'package main\nfunc main() {}',rust:'fn main() {}',kotlin:'fun main() {}',php:'<?php\n// Write your solution here',ruby:'# Write your solution here',swift:'import Foundation\n// Write your solution here',sql:'SELECT 1;'};

export function CodingPage() {
  const [language,setLanguage]=useState('java');
  const [code,setCode]=useState(START.java);
  const [output,setOutput]=useState('Ready.');
  const run=()=>{if(language!=='javascript'){setOutput('Secure multi-language execution will be connected to the backend code-runner service in the next phase.');return;}try{const w=new Worker(URL.createObjectURL(new Blob([`self.onmessage=e=>{try{const f=new Function(e.data);const r=f();self.postMessage({ok:true,r:String(r??"Execution completed")})}catch(x){self.postMessage({ok:false,r:String(x)})}}`],{type:'text/javascript'})));w.onmessage=e=>{setOutput(e.data.r);w.terminate()};w.postMessage(code)}catch(e){setOutput(String(e))}};
  return <main className="page"><section className="coding-shell"><div className="coding-toolbar"><div><p className="eyebrow">CODING INTERVIEW</p><h2>BerryBot Coding Lab</h2></div><select value={language} onChange={e=>{setLanguage(e.target.value);setCode(START[e.target.value]);setOutput(`${LANGS[e.target.value]} selected.`)}}>{Object.entries(LANGS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button className="primary-button" onClick={run}>▶ Run</button><button className="secondary-button">Submit</button></div><div className="coding-body"><div className="problem-panel"><p className="eyebrow">PROBLEM</p><h3>Build a solution and explain your approach.</h3><p>Input: [2, 7, 11, 15], target = 9</p><p>Expected: [0, 1]</p></div><div className="editor-panel"><Editor height="55vh" language={language==='cpp'?'cpp':language==='csharp'?'csharp':language} theme="vs-dark" value={code} onChange={v=>setCode(v??'')} options={{minimap:{enabled:false},fontSize:14,automaticLayout:true}}/><div className="output-panel"><strong>Execution / feedback</strong><pre>{output}</pre></div></div></div></section></main>;
}
